service: extract-excel-mics-list-by-cc-data # NOTE: update this with your service name

provider:
  name   : aws
  runtime: python3.6
  region : ap-south-1
  profile: serverless-admin
  timeout: 10
  memory : 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

custom:
  bucket: vjykrthk-extract-excel-data
  pythonRequirements:
    dockerizePip: true

functions:
  extract_excel_data:
    handler: handler.extract_excel_mics_list_by_cc_data
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .xls

plugins:
  - serverless-python-requirements
